version: "3"
services:
  app:
    container_name: sutm-app-prod
    build:
      context: ../
      dockerfile: docker/Dockerfile
    ports:
      - 8080:80
      - 631:631
    volumes:
      - ../src:/var/www/html
      - ../.env:/var/www/html/.env
      - /var/run/dbus:/var/run/dbus
        #- ./cupsd.conf:/etc/cups/cupsd.conf
    depends_on:
      - db
    command: sh -c "/etc/init.d/dbus start && /etc/init.d/avahi-daemon start && /etc/init.d/cups start && apache2ctl -D FOREGROUND "
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    env_file:
      - .env
    ports:
      - 8081:80
    environment:
      - PMA_HOST=db
      - PMA_USER=${PMA_USER}
      - PMA_PASSWORD=${PMA_PASSWORD}
    depends_on:
      - db
  db:
    container_name: sutm-db-dev
    image: mysql:latest
    env_file:
      - ../.env
    volumes:
      - ../../mysql-data:/var/lib/mysql
