version: "3"
services:
  app:
    container_name: sutm-app-prod
    build:
      context: ../
      dockerfile: docker/Dockerfile
    ports:
      - 8080:80
    volumes:
      - ../src:/var/www/html
      - ../.env:/var/www/html/.env
      - ../carpetas/impresion:/var/www/html/impresion
      - ../carpetas/facturas:/var/www/html/facturas
      - ../carpetas/documentos:/var/www/html/documentos
    depends_on:
      - db
    command: sh -c "apache2ctl -D FOREGROUND "
  phpmyadmin:
    container_name: sutm-phpmyadmin-prod
    image: phpmyadmin/phpmyadmin
    env_file:
      - ../.env
    ports:
      - 8081:80
    depends_on:
      - db
  db:
    container_name: sutm-db-prod
    image: mysql:latest
    env_file:
      - ../.env
    ports:
      - 3306:3306
    volumes:
      - ../../mysql-data:/var/lib/mysql
