version: '3'
services:
  app:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    ports:
      - 8080:80
    volumes:
      - ../src:/var/www/html
      - ../.env:/var/www/html/.env
    depends_on:
      - db
    command: php -S 0.0.0.0:80 -t /var/www/html
  db:
    image: mysql:latest
    env_file:
      - ../.env
