version: '3'
services:
  app:
    container_name: sutm-app-prod
      #network_mode: host
    build:
      context: ../
      dockerfile: docker/Dockerfile
    ports:
      - 8080:80
    volumes:
      - ../src:/var/www/html
      - ../.env:/var/www/html/.env
      - ./cupsd.conf:/etc/cups/cupsd.conf
    depends_on:
      - db
    command: sh -c "apache2ctl -D FOREGROUND && cupsd -f"
  db:
    container_name: sutm-db-dev
    image: mysql:latest
    env_file:
      - ../.env
    volumes:
      - ../../mysql-data:/var/lib/mysql
